"""empty message

Revision ID: 035ab0293918
Revises: 8b699fb33a75
Create Date: 2021-10-15 05:59:17.113440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035ab0293918'
down_revision = '8b699fb33a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_company',
    sa.Column('id_empresa_maritima', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_empresa_maritima'),
    sa.UniqueConstraint('nome_fantasia')
    )
    op.drop_constraint('containers_id_empresa_maritima_fkey', 'containers', type_='foreignkey')
    op.create_foreign_key(None, 'containers', 'shipping_company', ['id_empresa_maritima'], ['id_empresa_maritima'], ondelete='cascade')
    op.drop_constraint('navios_id_empresa_maritima_fkey', 'navios', type_='foreignkey')
    op.create_foreign_key(None, 'navios', 'shipping_company', ['id_empresa_maritima'], ['id_empresa_maritima'], ondelete='cascade')
    op.drop_table('empresa_maritima')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'navios', type_='foreignkey')
    op.create_foreign_key('navios_id_empresa_maritima_fkey', 'navios', 'empresa_maritima', ['id_empresa_maritima'], ['id_empresa_maritima'], ondelete='CASCADE')
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.create_foreign_key('containers_id_empresa_maritima_fkey', 'containers', 'empresa_maritima', ['id_empresa_maritima'], ['id_empresa_maritima'], ondelete='CASCADE')
    op.create_table('empresa_maritima',
    sa.Column('id_empresa_maritima', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_criacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='empresa_maritima_id_usuario_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_empresa_maritima', name='empresa_maritima_pkey'),
    sa.UniqueConstraint('nome_fantasia', name='empresa_maritima_nome_fantasia_key')
    )
    op.drop_table('shipping_company')
    # ### end Alembic commands ###
