"""add column is_port in User

Revision ID: 0f8dc9223d61
Revises: 9b19ea1e56e2
Create Date: 2021-10-18 10:56:00.276790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8dc9223d61'
down_revision = '9b19ea1e56e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_harbor', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_harbor = false WHERE is_harbor is NULL")
    op.alter_column("users", "is_harbor", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_harbor')
    # ### end Alembic commands ###
