"""empty message

Revision ID: 9b19ea1e56e2
Revises: 5a1a46eafefa
Create Date: 2021-10-16 09:48:52.177934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b19ea1e56e2'
down_revision = '5a1a46eafefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=512), nullable=True))
    op.execute("UPDATE users SET password_hash = md5(random()::text) WHERE password_hash is NULL")
    op.alter_column("users", "password_hash", nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=127), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
