"""alter column tracking_code by container_modelel

Revision ID: d931207705a8
Revises: 92b92798fd3e
Create Date: 2021-10-19 12:27:25.834493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd931207705a8'
down_revision = '92b92798fd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harbor', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'harbor', 'users', ['id_user'], ['id_user'], ondelete='cascade')
    op.add_column('travel', sa.Column('travel_code', sa.String(length=127), nullable=True))
    op.drop_constraint('travel_code_key', 'travel', type_='unique')
    op.drop_constraint('travel_destination_key', 'travel', type_='unique')
    op.create_unique_constraint(None, 'travel', ['travel_code'])
    op.drop_column('travel', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'travel', type_='unique')
    op.create_unique_constraint('travel_destination_key', 'travel', ['destination'])
    op.create_unique_constraint('travel_code_key', 'travel', ['code'])
    op.drop_column('travel', 'travel_code')
    op.drop_constraint(None, 'harbor', type_='foreignkey')
    op.drop_column('harbor', 'id_user')
    # ### end Alembic commands ###
