"""empty message

Revision ID: f074e90e97f5
Revises: 
Create Date: 2021-10-15 00:50:21.459270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f074e90e97f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('porto',
    sa.Column('id_porto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('pais', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('teus', sa.Integer(), nullable=False),
    sa.Column('disponibilidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_porto'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('username')
    )
    op.create_table('empresa_maritima',
    sa.Column('id_empresa_maritima', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_empresa_maritima'),
    sa.UniqueConstraint('nome_fantasia')
    )
    op.create_table('containers',
    sa.Column('id_container', sa.Integer(), nullable=False),
    sa.Column('codigo_rastreio', sa.Integer(), nullable=False),
    sa.Column('teu', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('id_empresa_maritima', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa_maritima'], ['empresa_maritima.id_empresa_maritima'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_container'),
    sa.UniqueConstraint('codigo_rastreio')
    )
    op.create_table('navios',
    sa.Column('id_navio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('calado', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('nacionalidade', sa.String(length=50), nullable=False),
    sa.Column('id_empresa_maritima', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa_maritima'], ['empresa_maritima.id_empresa_maritima'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_navio'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('container_porto',
    sa.Column('id_container_viagem', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('id_container', sa.Integer(), nullable=True),
    sa.Column('id_porto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_container'], ['containers.id_container'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['id_porto'], ['porto.id_porto'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_container_viagem')
    )
    op.create_table('navio_porto',
    sa.Column('id_navio_porto', sa.Integer(), nullable=False),
    sa.Column('data_chegada', sa.Date(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('id_navio', sa.Integer(), nullable=True),
    sa.Column('id_porto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_navio'], ['navios.id_navio'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['id_porto'], ['porto.id_porto'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_navio_porto')
    )
    op.create_table('viagens',
    sa.Column('id_viagem', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('id_navio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_navio'], ['navios.id_navio'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_viagem'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('destino')
    )
    op.create_table('container_viagem',
    sa.Column('id_container_viagem', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('ultima_atualizacao', sa.Date(), nullable=False),
    sa.Column('id_container', sa.Integer(), nullable=True),
    sa.Column('id_viagem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_container'], ['containers.id_container'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['id_viagem'], ['viagens.id_viagem'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_container_viagem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_viagem')
    op.drop_table('viagens')
    op.drop_table('navio_porto')
    op.drop_table('container_porto')
    op.drop_table('navios')
    op.drop_table('containers')
    op.drop_table('empresa_maritima')
    op.drop_table('usuarios')
    op.drop_table('porto')
    # ### end Alembic commands ###
